import { Inter } from "next/font/google";
import "./globals.css";

import { AppWrapper } from "@/store/AppWrapper";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppWrapper>
          {children}

          <Toaster
            position="top-center"
            reverseOrder={false}
            toastOptions={{
              duration: 3000, // Set the duration in milliseconds (e.g., 3000ms for 3 seconds)
              style: {
                background: "#333",
                color: "#fff",
              },
              // Additional toast options can be added here
            }}
          />
        </AppWrapper>
      </body>
    </html>
  );
}
