import Image from "next/image";
import React from "react";
import { GoHomeFill } from "react-icons/go";
import { FaMagnifyingGlass } from "react-icons/fa6";
import { MdOutlineExplore } from "react-icons/md";
import { MdOutlineAddComment } from "react-icons/md";
import { IoSettingsSharp } from "react-icons/io5";

import { IoNotifications } from "react-icons/io5";

import LogoutButton from "@/components/buttons/logoutButton";
import Link from "next/link";
import ProfileButton from "@/components/buttons/Profile";
import UserObj from "@/components/user/user";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashBoardLayout({ children }) {
  return (
    <>
      <UserObj />
      <div className="bg-black h-screen text-white">
        <div
          className="absolute top-0 left-0 h-full  rounded-r-2xl md:w-1/7 xl:w-80 p-10 hidden md:block "
          style={{ boxShadow: "0 0 2px rgba(255, 255, 255, 1)" }}
        >
          <div className="my-8 relative">
            <Link href="/dashboard">
              <Image
                src="https://res.cloudinary.com/dmlhm8dwi/image/upload/v1682664216/Standard_Collection_8website-logo-sm_rj35e0.png"
                alt="avatar"
                width={100}
                height={100}
                className="mx-auto  hidden lg:block"
              />{" "}
            </Link>
            <Link href="/dashboard">
              <Image
                src="https://res.cloudinary.com/dmlhm8dwi/image/upload/v1682664216/Standard_Collection_8website-logo-sm_rj35e0.png"
                alt="avatar"
                width={35}
                height={35}
                className="mx-auto   lg:hidden"
              />
            </Link>

            <h1 className="text-center  hidden lg:block mt-2 text-2xl  xl:text-4xl">
              {" "}
              Instagram
            </h1>
          </div>

          <div className="my-5 flex flex-col justify-evenly h-auto">
            <Link
              href="/dashboard"
              className="flex items-center gap-3  mb-10 lg:mb-5"
            >
              <GoHomeFill style={{ height: "25px", width: "25px" }} />
              <h1 className="text-2xl hidden lg:block"> Home</h1>
            </Link>{" "}
            <Link
              href="/dashboard/search"
              className="flex items-center gap-3  mb-10 lg:mb-5"
            >
              <FaMagnifyingGlass style={{ height: "25px", width: "25px" }} />
              <h1 className="text-2xl hidden lg:block"> Search</h1>
            </Link>{" "}
            <Link
              href="/dashboard/explore"
              className="flex items-center gap-3  mb-10 lg:mb-5"
            >
              <MdOutlineExplore style={{ height: "25px", width: "25px" }} />
              <h1 className="text-2xl hidden lg:block"> Explore</h1>
            </Link>{" "}
            <Link
              href="/dashboard/create"
              className="flex items-center gap-3  mb-10 lg:mb-5"
            >
              <MdOutlineAddComment style={{ height: "25px", width: "25px" }} />
              <h1 className="text-2xl hidden lg:block"> Create</h1>
            </Link>{" "}
            <Link
              href="/dashboard/notifications"
              className="flex items-center gap-3  mb-10 lg:mb-5"
            >
              <IoNotifications style={{ height: "25px", width: "25px" }} />
              <h1 className="text-2xl hidden lg:block"> Notifications</h1>
            </Link>
            <Link
              href="/dashboard/settings"
              className="flex items-center gap-3  mb-10 lg:mb-5"
            >
              <IoSettingsSharp style={{ height: "25px", width: "25px" }} />
              <h1 className="text-2xl hidden lg:block"> Settings</h1>
            </Link>
            <Link
              href="/dashboard/profile"
              className="flex items-center gap-3  mb-10 lg:mb-5"
            >
              <ProfileButton />
              <h1 className="text-2xl hidden lg:block"> Profile</h1>
            </Link>
          </div>
          <div className="absolute bottom-5 text-2xl cursor-pointer">
            <LogoutButton />
          </div>
        </div>

        <div
          className="absolute md:hidden  top:0 h-12 w-full flex items-center justify-between bg-black z-10 "
          style={{ boxShadow: "0 0 2px rgba(255, 255, 255, 1)" }}
        >
          <div className="flex gap-2 ml-5">
            <Link href="/dashboard">
              <Image
                src="https://res.cloudinary.com/dmlhm8dwi/image/upload/v1682664216/Standard_Collection_8website-logo-sm_rj35e0.png"
                alt="avatar"
                width={35}
                height={35}
                className=" "
              />
            </Link>

            <h1 className=""> Instagram</h1>
          </div>
          <div className="mr-5 flex gap-5">
            <Link href="/dashboard/search">
              {" "}
              <FaMagnifyingGlass style={{ height: "25px", width: "25px" }} />
            </Link>
            <Link href="/dashboard/notifications">
              <IoNotifications style={{ height: "25px", width: "25px" }} />
            </Link>
          </div>
        </div>

        <div className=" absolute flex items-center w-full  h-12 justify-evenly md:hidden bottom-0 bg-black  z-10">
          <Link href="/dashboard">
            {" "}
            <GoHomeFill style={{ height: "25px", width: "25px" }} />
          </Link>
          <Link href="/dashboard/explore">
            {" "}
            <MdOutlineExplore style={{ height: "25px", width: "25px" }} />
          </Link>
          <Link href="/dashboard/create">
            {" "}
            <MdOutlineAddComment style={{ height: "25px", width: "25px" }} />
          </Link>
          <Link href="/dashboard/settings">
            {" "}
            <IoSettingsSharp style={{ height: "25px", width: "25px" }} />
          </Link>
          <Link href="/dashboard/profile">
            {" "}
            <ProfileButton />
          </Link>
        </div>

        <div className=" md:w-[60%] lg:w-[50%]  mx-auto pt-[60px]   md:pt-8 h-[100%] overflow-y-scroll   scrollbar">
          {children}
        </div>
      </div>
    </>
  );
}
